In [72]:
import numpy as np
import scipy.linalg as lin
import copy

In [73]:

def rnd_mat(a, b):
    return np.random.random((a, b))

def crt_rnd_d(n):
    x=np.array(np.random.random((1, n)))
    return np.diag(x[0])

def rnd_triu(n):
    return np.triu(rnd_mat(n ,n))

def rnd_tril(n):
    return np.tril(rnd_mat(n, n))

def crt_rk(n, m):
    if m==0:
        return np.zeros((n, n))
    A=np.random.randint(5, size=(n, m))-2.5
    B=copy.deepcopy(A)
    for i in range(n-m):
        x=np.random.randint(5, size=(m, 1))-2.5
        w=B@x
        A=np.hstack((A, w))
    return np.array(A, dtype=float)

def rnd_sing(n):
    r=np.random.randint(n)
    return crt_rk(n, r)

In [75]:
X=crt_rk(3, 1)
print(X)

[[-1.5  -0.75  2.25]
 [-2.5  -1.25  3.75]
 [ 1.5   0.75 -2.25]]


In [184]:
#Вероятность матрицы оказаться вырожденной:
eps=1.56e-16

N=100000
counter=0
for i in range(N):
    r=np.random.randint(2, 15)
    if lin.det(rnd_mat(r, r))<=eps:
        counter+=1
print(counter/N*100)

49.963


In [22]:
pi=3.14159265358979323846

def exp(x):
    k=1
    term=1
    sum=0
    while sum != sum + term:
            sum+=term
            term=term*x/k
            k+=1            
    return sum

def sin(x):
    k=3
    term=x
    sum=0
    while sum != sum + term:
            sum+=term
            term=-term*x*x/(k*(k-1))
            k+=2            
    return sum

def cos(x):
    k=2
    term=1
    sum=0
    while sum != sum + term:
            sum+=term
            term=-term*x*x/(k*(k-1))
            k+=2            
    return sum

def ln(x):
    k=1
    x=x-1
    term=x
    sum=0
    while sum != sum + term:
            sum+=term/k
            k+=1
            term=-term*x           
    return sum

def tg(x):
    return sin(x)/cos(x)

def ctg(x):
    return cos(x)/sin(x)

def arcsin(x):
    n=0
    k=0
    sum=0
    term=x

    while sum!= sum + term:
        sum+=term/(2*k+1)
        n+=2
        k+=1
        term=term*x*x*n*(n-1)/(k*k*4)
    return sum

def arccos(x):
    return pi/2 - arcsin(x)

def arctg(x):
    k=1
    sum=0
    term=x
    while sum!= sum + term:      
        sum+=term/(2*k-1)
        term=-term*x*x
        k+=1        
    return sum

def sh(x):
    return (exp(x)-exp(-x))/2

def ch(x):
    return (exp(x)+exp(-x))/2

def th(x):
    return sh(x)/ch(x)

def arth(x):  
    k=1
    sum=0
    term=x
    while sum!= sum + term:
        sum+=term/(2*k-1)
        term=term*x*x
        k+=1        
    return sum


In [21]:
#Вычисление машинного эпсилон

def exp_2(x):
    k=1
    term=1
    sum=0
    while sum != sum + term:
            sum+=term
            term=term*x/k
            k+=1            
    return term, sum

exp_2(1)[0]

1.5619206968586228e-16

In [27]:
import numpy as np
import scipy.linalg as lin
    

def L_1(x):
    return np.sum(abs(x))

def L_2(x):
    return np.sum(x**2)

def cubic(x):
    return np.max(abs(x))

def matL_1(A):
    coll=[]
    for i in range(np.shape(A)[1]):
        coll.append(np.sum(abs(A[:, i])))
    return np.max(coll)
    
def matL_2(A):
    return np.sqrt(np.max(lin.eigvals(A.T @ A)))

def matcc(A):
    coll=[]
    for i in range(np.shape(A)[0]):
        coll.append(np.sum(abs(A[i, :])))
    return np.max(coll)

def check(A):
    return lin.det(A)==0


def cnn_(mat_norm, A):
    if np.shape(A)[0]==np.shape(A)[1]:
        if lin.det(A):
            return mat_norm(lin.inv(A))*mat_norm(A)
        print("condition number is inf")
    print("got non-square matrix")
    


In [30]:
#Пример вычисления чисел обусловленности для разных норм
A=np.random.random((2, 2)) 
cnn_(L_1, A), cnn_(L_2, A), cnn_(cubic, A)

(5.721922304337434, 6.0450424311333615, 1.8206344580719316)

In [164]:
a=1e-10

def G_proc(B):
    A=copy.deepcopy(B)
    N=np.shape(A)[0]
    for i in range(N):
        if A[i][i]==0:
            for k in range(i+1, N):
                if A[k][i]!=0:
                    A[[i, k], : ]=A[[k, i], :]
                    break
        else:
            for j in range(i+1, N):
                A[j, :]-=A[i, :]*A[j][i]/A[i][i]
    return A

def calc_rk(A):
    B=copy.deepcopy(G_proc(A))
    n=np.shape(B)[0]
    ons=np.ones(n)
    rk=0
    while np.any(np.around(B[rk,:], 10)+ons!=ons):
        rk+=1
        if rk==n:
            break
    return rk

In [183]:

A=crt_rk(5, 2)
print(A, calc_rk(A), sep='\n')
A=G_proc(A)
print(A, calc_rk(A), sep='\n')


[[-1.5  0.5  1.  -1.5 -0.5]
 [ 0.5 -2.5  5.5 -3.  -1. ]
 [ 0.5 -2.5  5.5 -3.  -1. ]
 [-1.5 -1.5  6.  -4.5 -1.5]
 [-0.5 -2.5  7.  -4.5 -1.5]]
2
[[-1.50000000e+00  5.00000000e-01  1.00000000e+00 -1.50000000e+00
  -5.00000000e-01]
 [ 0.00000000e+00 -2.33333333e+00  5.83333333e+00 -3.50000000e+00
  -1.16666667e+00]
 [ 0.00000000e+00  0.00000000e+00  8.88178420e-16  0.00000000e+00
   0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  4.44089210e-16
   0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.77635684e-15  0.00000000e+00
   0.00000000e+00]]
2


In [139]:

def solve_sys(A, y):
    N=np.shape(A)[0]
    A=G_proc(np.hstack((A, y)))
    for i in range(N):
        A[i,: ]/=A[i][i]
    for i in range(N-1, -1, -1):
        for j in range(i-1, -1, -1):
            A[j,: ]-=A[i, : ]*A[j][i]
    return A[:, N]


In [12]:
N=50

y=np.array(np.random.randint(5, size=(N, 1))-2.5, dtype=float)
A=crt_rk(N, N)
print(np.shape(A))
calc_rk(A)
x=solve_sys(A, y)
dy= np.random.normal(0, 0.1, y.shape)
dx=solve_sys(A, dy)

print(dx)
print(x)
mu=L_1(dx)/L_2(x)*L_2(y)/L_2(dy)
print(cnn_(L_2, A)*cnn_(L_2, lin.inv(A)))
print(mu)

(50, 50)
50
50
50
[ 0.0302428  -0.40551942  0.17984904 -0.52121228  0.00590096  1.17058635
  0.76442764  0.1869499   1.05641358  1.14858959 -0.87297428  1.20110343
 -0.78210461  1.41962466  0.16770201 -0.12906487 -1.96959139  0.37981007
 -0.17777367 -0.44345483  0.06371148 -0.09595975 -0.20016522 -0.43320988
  0.36662728 -0.15207805 -0.2937725   0.20808693  0.54226977 -0.50874777
  0.13972892  0.00716503 -0.03748624  0.07176328 -0.0490477  -0.03767985
 -0.08773368  0.02887352  0.07913425 -0.06001863  0.01808577 -0.02364553
 -0.08266452 -0.07634304 -0.00452394  0.00273816  0.00768882 -0.01034744
  0.00314838 -0.00220067]
[-2.41518190e+01  5.52950759e+01 -2.47946240e+01  3.06383648e+01
  1.75150543e+01 -3.08695535e+01 -2.97730906e+01  1.95522101e+01
  1.40850607e+01  2.11929584e+01  5.91177925e+00  1.19304455e+01
 -9.96098328e+00  1.50193614e+01  4.02673164e+00 -2.50361409e-01
 -1.58426612e+01  6.92830943e-01 -7.67165158e+00 -2.97012483e+00
 -1.70519714e+00 -3.17561453e-02  7.98818108e-0